language: python
os: osx
python:
  - "2.7"
install:
  - git clone https://github.com/MacPython/terryfy
  - source terryfy/travis_tools.sh
  - get_python_environment  macpython 2.7.10
  - brew update
  - brew install pip
  - pip install pync
script:
  - python main.py -c DEC15 -i SRM\ University
